title: Dev Hub

markdown: kramdown

safe: true
lsi: false
highlighter: pygments

# If running at root dir (e.g. CNAME, remove this line)
baseurl: /dev-hub

permalink: /:categories/:year/:month/:day/:title
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

archive_path: /archive.html
categories_path: /categories.html
tags_path: /tags.html

swagger_doc_location: http://petstore.swagger.io/v2/swagger.json

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: "_posts"
    values:
      layout: post
