# CDN based on git tag, check https://github.com/swagger-api/swagger-ui for latest
cdn: https://cdn.rawgit.com/swagger-api/swagger-ui/f6be07ff9a46a7454d246649ca75cf7e19d4d618/dist/

css_deps:
  - "css/typography.css"
  - "css/reset.css"
  - "css/screen.css"

js_deps:
  - "lib/shred.bundle.js"
  - "lib/jquery-1.8.0.min.js"
  - "lib/jquery.slideto.min.js"
  - "lib/jquery.wiggle.min.js"
  - "lib/jquery.ba-bbq.min.js"
  - "lib/handlebars-2.0.0.js"
  - "lib/underscore-min.js"
  - "lib/backbone-min.js"
  - "lib/swagger-client.js"
  - "swagger-ui.js"
  - "lib/highlight.7.3.pack.js"
  - "lib/marked.js"
